[2024-05-16T12:03:14.001+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: goodreads_pipeline.Warehouse_data_quality_checks scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16T12:03:14.020+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: goodreads_pipeline.Warehouse_data_quality_checks scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16T12:03:14.021+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-16T12:03:14.049+0000] {taskinstance.py:2214} INFO - Executing <Task(DataQualityOperator): Warehouse_data_quality_checks> on 2024-05-15 00:00:00+00:00
[2024-05-16T12:03:14.060+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-05-16T12:03:14.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'goodreads_pipeline', 'Warehouse_data_quality_checks', 'scheduled__2024-05-15T00:00:00+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/goodreads_etl_pipeline.py', '--cfg-path', '/tmp/tmp_7h53m5t']
[2024-05-16T12:03:14.067+0000] {standard_task_runner.py:88} INFO - Job 406: Subtask Warehouse_data_quality_checks
[2024-05-16T12:03:14.160+0000] {task_command.py:423} INFO - Running <TaskInstance: goodreads_pipeline.Warehouse_data_quality_checks scheduled__2024-05-15T00:00:00+00:00 [running]> on host 4ceaa523915d
[2024-05-16T12:03:14.290+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='goodreads' AIRFLOW_CTX_DAG_ID='goodreads_pipeline' AIRFLOW_CTX_TASK_ID='Warehouse_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-15T00:00:00+00:00'
[2024-05-16T12:03:14.293+0000] {data_quality.py:27} INFO - Starting data quality validation on table : goodreads_warehouse.authors
[2024-05-16T12:03:14.319+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-05-16T12:03:17.233+0000] {sql.py:457} INFO - Running statement: select count(*) from goodreads_warehouse.authors;, parameters: None
[2024-05-16T12:03:34.251+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/data_quality.py", line 28, in execute
    records = redshift_hook.get_records("select count(*) from {};".format(table))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 267, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "goodreads_warehouse" does not exist

[2024-05-16T12:03:35.167+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=goodreads_pipeline, task_id=Warehouse_data_quality_checks, execution_date=20240515T000000, start_date=20240516T120314, end_date=20240516T120335
[2024-05-16T12:03:35.268+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 406 for task Warehouse_data_quality_checks (schema "goodreads_warehouse" does not exist
; 115)
[2024-05-16T12:03:35.300+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-16T12:03:35.443+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
